### ISSUE TITLE
LiteLLM と Langfuse を用いた LLM 利用状況の分析のコメント

### ISSUE THREAD

**Issue by koshian2** [littlemex/aws-samples#36]
### 2.サービスの起動

```console
# ポートフォワーディングの設定 (Local PC で実行してください)
../scripts/port_forward.py
```

この部分です。起動時のインスタンスIDが抜けているのではないでしょうか？

```console
python ../scripts/port_forward.py -i i-xxx
```

またプロファイルを指定する場合はこの39行目にこれを追加するのもいいと思います。ちゃんとやるなら引数で渡すですが

```python
    cmd = [
        "aws", "ssm", "start-session",
        "--target", instance_id,
        "--region", region,
        "--document-name", "AWS-StartPortForwardingSession",
        "--parameters", f"portNumber=[\"{remote_port}\"],localPortNumber=[\"{local_port}\"]",
        "--profile", "cline" # ここを追加
    ]
```

また、config.ymlに3000->3000のポートフォワーディングを追加するという指示が抜けています。これがないとlangfuseのコンソールが開けません

```yaml
ports:
  - local: 8080
    remote: 8080
  - local: 4000
    remote: 4000
  - local: 2222
    remote: 22
  - local: 3000
    remote: 3000
```
